apiVersion: v2
name: ibm-db2
version: 0.1.0
appVersion: 1.16.0
description: CNTK - IBM DB2 for SFG
dependencies:
  - name: service-account
    version: 0.5.0
    repository: https://charts.cloudnativetoolkit.dev
  - name: ibm-sfg-db2
    version: 0.1.0
    repository: https://hollisc.github.io/gitops-testing
