# (C) Copyright 2019 Syncsort Incorporated. All rights reserved.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "275"
  name: "ibm-b2bi-scc"
  labels:
    app: "ibm-b2bi-scc"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "ibm-b2bi-scc"
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
  namespace: b2bi
