# (C) Copyright 2019 Syncsort Incorporated. All rights reserved.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "ibm-b2bi-scc"
  labels:
    app: "ibm-b2bi-scc"
  annotations:
    argocd.argoproj.io/sync-wave: "270"
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - "ibm-b2bi-scc"
  resources:
  - securitycontextconstraints
  verbs:
  - use
