kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "270"
  name: sterlingb2bitoolkit-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
