# (C) Copyright 2019 Syncsort Incorporated. All rights reserved.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "275"
  name: "ibm-pem-scc-pem"
  labels:
    app: "ibm-pem-scc"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "ibm-pem-scc"
subjects:
- kind: ServiceAccount
  name: pem
  namespace: pem
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "275"
  name: "default-anyuid-pem"
  labels:
    app: "ibm-pem-scc"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "ibm-pem-anyuid-scc"
subjects:
- kind: ServiceAccount
  name: default
  namespace: pem