apiVersion: v2
name: ibm-automation-foundation-core-operator
description: A Helm chart for Kubernetes
type: application
version: "1.0.0"
appVersion: "1.0"
dependencies:
  - name: ocp-subscription
    version: "1.0.0"
    repository: https://charts.cloudnativetoolkit.dev
