apiVersion: v2
name: ibm-pem
version: 0.1.0
appVersion: 1.16.0
description: IBM Partner Engagement Manager 6.1.0.0
dependencies:
  - name: service-account
    version: 0.5.0
    repository: https://charts.cloudnativetoolkit.dev
  - name: ibm-pem-standard-vbudi
    version: 1.0.2
    repository: https://vbudi000.github.io/gitops-helm-repo