apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana-instana
  labels:
    app: grafana
spec:
  deployment:
    env:
    # GF_INSTALL_PLUGINS is used to name the plugins to be installed
    # <plugin-name> <plugin-version> is the appropriate syntax
      - name: GF_INSTALL_PLUGINS
        value: instana-datasource 3.3.1
      - name: DASHBOARD_NAMESPACES_ALL
        value: "true"
    envFrom:
      - secretRef:
          name: instana-backend
    skipCreateAdminAccount: false
  ingress:
    enabled: True
  config:
    log:
      mode: "console"
      level: "warn"
    auth:
      disable_login_form: False
      disable_signout_menu: False
    auth.anonymous:
      enabled: True
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [ grafana ] }      