apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cp4a-operator-catalog-subscription
spec:
  channel: v21.1
  installPlanApproval: Automatic
  name: ibm-cp4a-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
