apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-automation-foundation
spec:
  channel: v1.0
  config:
    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 150m
        memory: 200Mi
  installPlanApproval: Automatic
  name: ibm-automation
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
