apiVersion: v2
name: sealed-operator
description: A Helm chart for Kubernetes
type: application
version: 1.16.0
appVersion: v0.16.0
dependencies:
  - name: sealed-secrets
    version: 1.16.1
    repository: https://bitnami-labs.github.io/sealed-secrets