apiVersion: v2
name: ibm-automation-foundation-core-operator
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: "1.2"
dependencies:
  - name: ibm-automation-foundation-core-operator
    version: 0.1.2
    repository: https://charts.cloudnativetoolkit.dev
