global: {}

oadp-instance:
  oadp:
    name: oadp-velero
    spec:
      default_velero_plugins:
        - aws
        - openshift
      enable_restic: false
      olm_managed: true
      use_upstream_images: false
      velero_resource_allocation:
        limits:
          cpu: '1'
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 256Mi